use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, sqlx::FromRow)]
pub struct User {
    #[sqlx(rename = "userName")]
    pub username: String,
    pub stars: i32,
    pub demons: i32,
    pub diamonds: i32,
    pub coins: i32,
    #[sqlx(rename = "userCoins")]
    pub user_coins: i32,
    #[sqlx(rename = "creatorPoints")]
    pub creator_points: i32,
    #[sqlx(rename = "accIcon")]
    pub acc_icon: i32,
    #[sqlx(rename = "accShip")]
    pub acc_ship: i32,
    #[sqlx(rename = "accBall")]
    pub acc_ball: i32,
    #[sqlx(rename = "accBird")]
    pub acc_bird: i32,
    #[sqlx(rename = "accDart")]
    pub acc_dart: i32,
    #[sqlx(rename = "accRobot")]
    pub acc_robot: i32,
    #[sqlx(rename = "accSpider")]
    pub acc_spider: i32,
    #[sqlx(rename = "accGlow")]
    pub acc_glow: i32,
    #[sqlx(rename = "accExplosion")]
    pub acc_explosion: i32,
    pub color1: i32,
    pub color2: i32,
    pub icon: i32,
    #[sqlx(rename = "iconType")]
    pub icon_type: i32,
    pub special: i32,
}
